#!/bin/bash

[ "$1" = "usage" ] && helpcmd=`basename $0`
[ "$2" = "-h" ] || [ "$2" == "--help" ] && helpcmd="$1"

if [ $helpcmd ]
then
  cat << EOF
    $helpcmd [TERM...]
      same as the original ls command (with the date).
EOF
	exit 0
fi

shift

_list "$TODO_FILE" "$@"
